// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTwPiSKkx0uadYAmpXpkNxVn6zBm6OuhM',
    appId: '1:522189466074:android:cdee461e79c487b5cf38e3',
    messagingSenderId: '522189466074',
    projectId: 'mscanner-30033',
    storageBucket: 'mscanner-30033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDG_Xb01QmvFeK5lXbmcdA-13b736ojOU',
    appId: '1:522189466074:ios:3e3f59ffdf25b1b7cf38e3',
    messagingSenderId: '522189466074',
    projectId: 'mscanner-30033',
    storageBucket: 'mscanner-30033.appspot.com',
    androidClientId: '522189466074-bi0pvlhbqpmeo6i6q8r4l268tvlngd8l.apps.googleusercontent.com',
    iosClientId: '522189466074-gneqoeov3c4hgbd61jgnv2euhdrkihqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.currency2',
  );
}
